# Generated by Django 3.1.11 on 2021-06-05 20:32

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210605_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Firebase User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('country_code', 'mobile_number')},
        ),
    ]
